# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c607bff26583f45692a95e7c71bbd61515121f4d4e75ab14735bb31903f8de0305649292e3a76a10800b9e62c12dadf1b66e319eb401b60cc8907b3db09cbda

test:
  secret_key_base: b62d7005a0c1e474180c2de56ffe24a6742e0f781efb53aca7f382882933a183f05fc16e80f50ab35af9aeb4207eefeb4706b84c42891f09b541b0980fbc1ab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
